# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages
latex: false

r:
- 3.1:
  - warnings_are_errors: false
- 3.2
- 3.3
- 3.4
- release
- devel

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"

after_success:
  - Rscript -e 'covr::codecov()'
